#! /bin/bash
echo Read and parse data from KCDC site
./COVID19KoreaData.wls > ../src/output/korea-corona19-data.csv
echo Generate Korea Corona19 status
./COVID19KoreaStat.wls > ../src/output/korea-corona19-stat.svg
echo Generate Korea Corona19 breakdown map
./COVID19KoreaBreakdown.wls > ../src/output/korea-corona19-breakdown.svg
echo Generate Korea Corona19 trend map
./COVID19KoreaTrend.wls > ../src/output/korea-corona19-trend.svg
echo Read and parse data from Seoul site
./COVID19SeoulData.wls > ../src/output/seoul-corona19-data.csv
echo Generate Seoul Corona19 growth map
./COVID19SeoulGrowth.wls > ../src/output/seoul-corona19-growth.svg   
echo Generate Seoul Corona19 delta map   
./COVID19SeoulDelta.wls > ../src/output/seoul-corona19-delta.svg
echo Generate Seoul Corona19 age histogram
./COVID19SeoulByAge.wls > ../src/output/seoul-corona19-by-age.svg
echo Generate Seoul Corona19 gender chart
./COVID19SeoulByGender.wls > ../src/output/seoul-corona19-by-gender.svg
echo Generate Seoul Corona19 district map
./COVID19SeoulByDistrict.wls > ../src/output/seoul-corona19-by-district.svg
echo Done...