#! /bin/bash
echo 'Collect data and Generate output for corona19korea.com'
if [[ $1 == all || $1 == 'korea' ]]; then
    echo '------------------'
    ./COVID19Korea.wls
fi
if [[ $1 == all || $1 == 'seoul' ]]; then
    echo '------------------'
    ./COVID19Seoul.wls
fi
if [[ $1 == all || $1 == 'gyeonggi' ]]; then
    echo '------------------'
    ./COVID19Gyeonggi.wls
fi
if [[ -z $1 ]]; then
    echo 'Usage: build (all | seoul | gyeonggi)'
else
    echo '------------------'
    echo 'Done.'
fi